In [1]:
import torch 


In [29]:
x = torch.ones(5)
y= torch.zeros(3)
#requires_grad : 변수들에 대한 손실 함수를 계산하기위해서 require_grad를 활성화 함.
# 단 성능 상의 이유로 backward 연산은 한 번만 수행할 수 있음
w = torch.randn(5,3,requires_grad=True)
b= torch.randn(3, requires_grad=True)
z= torch.matmul(x,w)+b
# 역전파 : 매개변수는 주어진 매개변수에 대한 손실 함수의 변화도에 따라 조정
# pytorch에 autograd라고 불리는 자동 미분 엔진이 내장되어 있슴

loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)



In [34]:

print(z.grad_fn)
print(loss.grad_fn)
print(z)
print(w)
print(b)

tensor([ 1.5258,  2.1986, -3.8160], grad_fn=<AddBackward0>)
tensor([[ 1.2525,  1.0015, -2.2478],
        [ 1.3078,  0.7054, -0.0174],
        [-0.9001, -0.3161, -0.0475],
        [ 0.2617,  0.9605, -1.8179],
        [-0.8098, -0.7016, -0.2036]], requires_grad=True)
tensor([0.4137, 0.5488, 0.5183], requires_grad=True)


In [31]:
# 변화도 계산하기
loss.backward()
#require_grad = True가 되어 있는 변수들
print(w.grad)
print(b.grad)

tensor([[0.2738, 0.3000, 0.0072],
        [0.2738, 0.3000, 0.0072],
        [0.2738, 0.3000, 0.0072],
        [0.2738, 0.3000, 0.0072],
        [0.2738, 0.3000, 0.0072]])
tensor([0.2738, 0.3000, 0.0072])


In [37]:
z = torch.matmul(x,w)+b
print(z.requires_grad)

# torch.no_grad() 블록으로 둘러싸서 연산 추적을 멈출 수 있음 = detach()를 사용하면 됨
with torch.no_grad():
    z = torch.matmul(x,w)+b
print(z.requires_grad)


# 변화도 추적을 멈춰야 할 때
# 신경망 일부 매개변수를 고정된 매개변수로 표시
# 변화도를 추적하지 않는 텐서의 연산이 더 효율적이기 때문에, 순전파 단계만 수행할 때 연산 속도가 향상됨

True
False


In [ ]:
inp = torch.eye(5,requires_grad=True)
out = (int+1).pow(2)
out.backward(torch.ones_like(inp), retain_graph = True)
print(inp.grad)
out.backward(torch.ones_like(inp), retain_graph = True)
print(inp.grad)
inp.grad.zero_()
out.backward(torch.ones_like(inp), retain_graph = True)
print(inp.grad)