In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


In [2]:
device ='cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [3]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        # nn.flatten : 계층을 초기화하여 각 28*28의 2D 이미지를 784 픽셀 값을 갖는 연속된 배열로 변환
        self.flatten = nn.Flatten()
        # nn.Sequential : 순서를 갖는 모듈의 컨테이너, 정의된 것과 같은 순서로 모든 모듈들을 통해 전달됨
        self.linear_relu_stack = nn.Sequential(
            # nn.Linear : 저장된 가중치(weights)와 편향(bias)을 사용하여 입력에 선형 변환을 적용하는 모듈
            nn.Linear(28*28,512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10),
            nn.ReLU(),

        )
    def forward(self,x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


In [4]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)


In [31]:
X = torch.rand(1,28,28,device=device)
logits = model(X)
# nn.Softmax : [-infty, infty] 범위의 원시 값인 logits를 반환, logits는 각 분류에 대한 예측 확률을 나타내도록 [0,1] 범위로 비례하여 조정됩니다.
# dim 매개변수는 값의 합이 1이 되는 차원을 나타냅니다.
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(y_pred)


tensor([9], device='cuda:0')


In [32]:
input_image = torch.rand(3,28,28)
print(input_image.size())

torch.Size([3, 28, 28])


In [34]:
flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())


torch.Size([3, 784])


In [39]:
layer1= nn.Linear(in_features=28*28, out_features=20)
print(layer1)
hidden1 = layer1(flat_image)
print(hidden1.size())

Linear(in_features=784, out_features=20, bias=True)
torch.Size([3, 20])


In [40]:
print(hidden1)
hidden1 = nn.ReLU()(hidden1)
print(hidden1)

tensor([[-0.0646,  0.1130, -0.3668,  0.1389, -0.2489, -0.1643, -0.6580,  0.1363,
          0.0404, -0.5888,  0.0356, -0.0734, -0.0793,  0.4106,  0.0047, -0.4806,
         -0.0192, -0.2542, -0.1858,  0.2267],
        [-0.3355, -0.1899, -0.0873,  0.1058, -0.0967, -0.4359, -0.4994, -0.1120,
          0.0045, -0.4296, -0.1654, -0.2725, -0.0208,  0.2064,  0.4164, -0.2841,
          0.0816, -0.4417,  0.1853, -0.1194],
        [-0.1119,  0.1023, -0.1721,  0.2667, -0.4029, -0.4360, -0.6732,  0.1995,
          0.1464, -0.3699,  0.0470, -0.0972, -0.0007,  0.1473,  0.2630, -0.3249,
         -0.0272, -0.1093, -0.2946, -0.2785]], grad_fn=<AddmmBackward0>)
tensor([[0.0000, 0.1130, 0.0000, 0.1389, 0.0000, 0.0000, 0.0000, 0.1363, 0.0404,
         0.0000, 0.0356, 0.0000, 0.0000, 0.4106, 0.0047, 0.0000, 0.0000, 0.0000,
         0.0000, 0.2267],
        [0.0000, 0.0000, 0.0000, 0.1058, 0.0000, 0.0000, 0.0000, 0.0000, 0.0045,
         0.0000, 0.0000, 0.0000, 0.0000, 0.2064, 0.4164, 0.0000, 0.0816, 0.0000,

In [42]:
seq = nn.Sequential(
    flatten, layer1, nn.ReLU(),nn.Linear(20,10)
)
input_image = torch.rand(3,28,28)
logits = seq(input_image)

In [43]:
logits

tensor([[-0.0270,  0.0833,  0.1634, -0.0961,  0.0361,  0.0052, -0.2553, -0.1374,
         -0.1107,  0.2284],
        [ 0.0415,  0.1113,  0.2655, -0.1363,  0.1100,  0.0056, -0.2988, -0.2807,
         -0.0636,  0.1316],
        [ 0.0932,  0.1542,  0.1972, -0.1027,  0.0642, -0.0396, -0.2530, -0.2225,
         -0.0834,  0.1930]], grad_fn=<AddmmBackward0>)