In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data 

tensor([[1, 2],
        [3, 4]])

In [10]:
np_array = np.array(data)
print(np_array)
x_np = torch.from_numpy(np_array)
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [11]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand= torch.rand_like(x_data,dtype=torch.float64)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.5188, 0.4497],
        [0.5925, 0.7458]], dtype=torch.float64)


In [12]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")


Random Tensor: 
 tensor([[0.7273, 0.8909, 0.2253],
        [0.3375, 0.4001, 0.2837]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
if torch.cuda.is_available():
    tensor= tensor.to('cuda')

    

In [16]:
tensor[:,1] = 0
print(tensor)

tensor([[0.3648, 0.0000, 0.4649, 0.1377],
        [0.0366, 0.0000, 0.5773, 0.3359],
        [0.1240, 0.0000, 0.2722, 0.4524]], device='cuda:0')


In [17]:
t1 = torch.cat([tensor,tensor,tensor],dim=1)
print(t1)

tensor([[0.3648, 0.0000, 0.4649, 0.1377, 0.3648, 0.0000, 0.4649, 0.1377, 0.3648,
         0.0000, 0.4649, 0.1377],
        [0.0366, 0.0000, 0.5773, 0.3359, 0.0366, 0.0000, 0.5773, 0.3359, 0.0366,
         0.0000, 0.5773, 0.3359],
        [0.1240, 0.0000, 0.2722, 0.4524, 0.1240, 0.0000, 0.2722, 0.4524, 0.1240,
         0.0000, 0.2722, 0.4524]], device='cuda:0')


In [22]:
# 행렬 곱
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)

torch.matmul(tensor, tensor.T, out=y3)
print(y1)
print(y2)
print(y3)
print(tensor)

tensor([[0.3681, 0.3279, 0.2341],
        [0.3279, 0.4473, 0.3136],
        [0.2341, 0.3136, 0.2941]], device='cuda:0')
tensor([[0.3681, 0.3279, 0.2341],
        [0.3279, 0.4473, 0.3136],
        [0.2341, 0.3136, 0.2941]], device='cuda:0')
tensor([[0.3681, 0.3279, 0.2341],
        [0.3279, 0.4473, 0.3136],
        [0.2341, 0.3136, 0.2941]], device='cuda:0')
tensor([[0.3648, 0.0000, 0.4649, 0.1377],
        [0.0366, 0.0000, 0.5773, 0.3359],
        [0.1240, 0.0000, 0.2722, 0.4524]], device='cuda:0')


/tmp/ipykernel_11130/1949155730.py:5: UserWarning: An output with one or more elements was resized since it had shape [3, 4], which does not match the required output shape [3, 3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  /opt/conda/conda-bld/pytorch_1634272068694/work/aten/src/ATen/native/Resize.cpp:23.)
  torch.matmul(tensor, tensor.T, out=y3)


In [23]:
z1 = tensor * tensor 
print(z1)
z2 = tensor.mul(tensor)
print(z2)
z3=torch.rand_like(tensor)
print(z3)
torch.mul(tensor, tensor, out=z3)



tensor([[0.1331, 0.0000, 0.2161, 0.0190],
        [0.0013, 0.0000, 0.3332, 0.1128],
        [0.0154, 0.0000, 0.0741, 0.2046]], device='cuda:0')
tensor([[0.1331, 0.0000, 0.2161, 0.0190],
        [0.0013, 0.0000, 0.3332, 0.1128],
        [0.0154, 0.0000, 0.0741, 0.2046]], device='cuda:0')
tensor([[0.7194, 0.7148, 0.5007, 0.0875],
        [0.8376, 0.2766, 0.0569, 0.5834],
        [0.5780, 0.7049, 0.4978, 0.0477]], device='cuda:0')


tensor([[0.1331, 0.0000, 0.2161, 0.0190],
        [0.0013, 0.0000, 0.3332, 0.1128],
        [0.0154, 0.0000, 0.0741, 0.2046]], device='cuda:0')

In [24]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

2.7656161785125732 <class 'float'>


In [25]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[0.3648, 0.0000, 0.4649, 0.1377],
        [0.0366, 0.0000, 0.5773, 0.3359],
        [0.1240, 0.0000, 0.2722, 0.4524]], device='cuda:0') 

tensor([[5.3648, 5.0000, 5.4649, 5.1377],
        [5.0366, 5.0000, 5.5773, 5.3359],
        [5.1240, 5.0000, 5.2722, 5.4524]], device='cuda:0')


In [26]:
t= torch.ones(5)
print(t)

n = t.numpy()
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [27]:
t.add_(1)
print(t,"\n",n)

tensor([2., 2., 2., 2., 2.]) 
 [2. 2. 2. 2. 2.]
